# XcodeGen - génère un projet Xcode valide (xcodegen generate)
# Voir CONSOLE.md pour toutes les commandes.

name: MyEventNative
options:
  bundleIdPrefix: com.myevent
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_NSContactsUsageDescription: "MyEvent utilise tes contacts pour inviter des personnes à tes événements."
    INFOPLIST_KEY_SUPABASE_URL: "https://YOUR_PROJECT.supabase.co"
    INFOPLIST_KEY_SUPABASE_ANON_KEY: "YOUR_ANON_KEY"

targets:
  MyEventNative:
    type: application
    platform: iOS
    sources:
      - path: MyEventNative
        name: MyEventNative
        excludes:
          - "Info.plist"
    settings:
      base:
        INFOPLIST_FILE: MyEventNative/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.myevent.native
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
    dependencies: []
    info:
      path: MyEventNative/Info.plist
    additionalFiles:
      - path: MyEventNative/Info.plist
    frameworks:
      - Contacts.framework
      - ContactsUI.framework
      - PhotosUI.framework
